import{S as d,i as c}from"./assets/vendor-5ObWk2rO.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&e(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function e(r){if(r.ep)return;r.ep=!0;const t=s(r);fetch(r.href,t)}})();function u(o,i){const s=o.map(e=>`<li class="imgAdded">
                <a href="${e.largeImageURL}" class="gallery-item"> 
                    <img src="${e.webformatURL}" alt="${e.tags}" width="360" height="152">
                </a>
                <div class="descr">
                    <p><b>Likes</b> ${e.likes}</p>
                    <p><b>Views</b> ${e.views}</p>
                    <p><b>Comments</b> ${e.comments}</p>
                    <p><b>Downloads</b> ${e.downloads}</p>
                </div>
            </li>`).join("");i.insertAdjacentHTML("beforeend",s)}function m(o){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"45999766-9f9a6b82db6e56573d0cf5f49",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}).toString()}`;return fetch(s).then(e=>{if(!e.ok)throw new Error(`HTTP error! Status: ${e.status}`);return e.json()}).then(e=>e.hits).catch(e=>{console.error("Fetch error:",e)})}const f=new d(".list-img a"),h=document.querySelector(".formImg"),l=document.querySelector(".list-img"),n=document.querySelector(".loader"),g=document.getElementById("search-img");h.addEventListener("submit",o=>{o.preventDefault(),l.innerHTML="",n.classList.remove("visually-hidden");const i=g.value.trim();i!==""?m(i).then(s=>{n.classList.add("visually-hidden"),s.length>0?(u(s,l),f.refresh()):c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(s=>{n.classList.add("visually-hidden"),c.error({title:"Error",message:"Error fetching images. Try again later.",position:"topRight"}),console.error(s)}):(n.classList.add("visually-hidden"),c.error({title:"Error",message:"Please enter a search term!",position:"topRight"}))});
//# sourceMappingURL=index.js.map
