import{S as p,i as f}from"./assets/vendor-BrddEoy-.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const g="46086824-2983fdd94aba44351510a0e76",h="https://pixabay.com/api/";async function y(t,n=1,i=12){const o=`${h}?key=${g}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${i}`,e=await fetch(o);if(!e.ok)throw new Error("Error fetching images from Pixabay");return await e.json()}function b(t,n){const i=t.map(({webformatURL:o,largeImageURL:e,tags:r,likes:s,views:u,comments:d,downloads:m})=>`
        <a href="${e}" class="gallery-item">
          <img src="${o}" alt="${r}" loading="lazy" />
          <div class="info">
            <p><b>Likes</b>: ${s}</p>
            <p><b>Views</b>: ${u}</p>
            <p><b>Comments</b>: ${d}</p>
            <p><b>Downloads</b>: ${m}</p>
          </div>
        </a>`).join("");n.innerHTML=i,L()}function L(){new p(".gallery a",{captionDelay:250}).refresh()}function a(t){f.error({title:"Error",message:t})}function w(t){f.info({title:"Info",message:t})}function $(t){t.classList.remove("hidden")}function E(t){t.classList.add("hidden")}const S=document.getElementById("search-form"),c=document.querySelector(".gallery"),l=document.getElementById("loading-spinner");S.addEventListener("submit",async t=>{t.preventDefault();const n=document.getElementById("query").value.trim();if(!n){a("Search query cannot be empty!");return}c.innerHTML="",$(l);try{const o=(await y(n)).hits;o.length===0?w("Sorry, there are no images matching your search query."):b(o,c)}catch{a("Something went wrong. Please try again later.")}finally{E(l)}});
//# sourceMappingURL=index.js.map
